name: pingpong_sample
description: "A new project for pingpong"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  equatable: ^2.0.5
  get_it: ^7.6.7
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.2
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  flutter_svg: ^2.0.17
  modal_bottom_sheet: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.14



flutter:


  uses-material-design: true

